### ISSUE TITLE
Update backend port in CONTRIBUTING.md

### ISSUE THREAD

**Issue by XDRAGON2002** [XDRAGON2002/iiit-gram#14]
Currently the CONTRIBUTING.md reads that the server will run on port 5000, this has been changed in a recent PR, now it will run on port 8080 instead, this needs to be updated in the documents.

**Comment by najeebkp** [comment]
hi @XDRAGON2002 please assign this to me

**Comment by XDRAGON2002** [comment]
Hi @najeebkp! Happy Hacktober!

This repo is actually supposed to be part of an educational event being organized in our institute for the students to teach them more about opensource and contributions in general, though I'm sure you'll be able to find a bunch of issues to work on in other repositories!

**Comment by Vishvam10** [comment]
Hi @XDRAGON2002 ! I can work on this. Please assign this task to me.

**Comment by XDRAGON2002** [comment]
Hi @Vishvam10 as stated above this issue for students of our institute only.

**Comment by Vishvam10** [comment]
I see.

**Comment by Aaroh1** [comment]
Hey @XDRAGON2002! Could you please assign this issue to me?

**Comment by XDRAGON2002** [comment]
Sure @Aaroh1 go ahead!

**Comment by iamhariom0228** [comment]
Hey @XDRAGON2002  sir, can I  work on it?

**Comment by XDRAGON2002** [comment]
@iamhariom0228 This issue has been assigned to @Aaroh1 if he doesn't want to work on this anymore then you can take this up.
