### ISSUE TITLE
Change default port of backend to 8080 instead of 5000

### ISSUE THREAD

**Issue by XDRAGON2002** [XDRAGON2002/iiit-gram#2]
Some Mac users might experience problems in running a service on port 5000 so needs to switch to 8080.

**Comment by XDRAGON2002** [comment]
Hi @sethisagar! Happy Hacktoberfest!

This repository is an exercise for the students of our institute so they can get to learn more about opensource, hence cannot be allotted to people outside the institute, however I'm sure you'll be able to find a plethora of issues in other repositories!

**Comment by romantic-sid** [comment]
plz assign me this issue sir

**Comment by XDRAGON2002** [comment]
Sure
