### ISSUE TITLE
Add a readme.md

### ISSUE THREAD

**Issue by ImAnshuJoshi** [XDRAGON2002/iiit-gram#21]
Proper readme file for the installation of the project to the local is needed. I would like to do this . Can you assign this to me?

**Comment by XDRAGON2002** [comment]
@ImAnshuJoshi Can you specify what is missing in the README file that you wish to add?

**Comment by ImAnshuJoshi** [comment]
@XDRAGON2002 , my bad , i didnt see it properly . Closing the issue
