### ISSUE TITLE
Add mock data to users array

### ISSUE THREAD

**Issue by XDRAGON2002** [XDRAGON2002/iiit-gram#4]
The users array includes mock data for creating routes until MongoDB is setup, we require a new field `id` to be added to each object in the array before the name attribute, this `id` must be unique in nature (eg. '1', '2', '3' etc).

**Comment by romantic-sid** [comment]
sir plz assign me this issue

**Comment by XDRAGON2002** [comment]
@romantic-sid you should work on one issue at a time, I'll assign this once you finish the other one.

**Comment by XDRAGON2002** [comment]
@romantic-sid do you want to work on this?

**Comment by romantic-sid** [comment]
Yes sir
