### ISSUE TITLE
Create new route `/users/update/<id>`

### ISSUE THREAD

**Issue by XDRAGON2002** [XDRAGON2002/iiit-gram#7]
Create a PUT route handler that updates the data for the specified id in the users array.

**Comment by romantic-sid** [comment]
plz assign me this issue

**Comment by XDRAGON2002** [comment]
I'll assign you once you finish your open PR.

**Comment by iamhariom0228** [comment]
hey @XDRAGON2002, can I take up this issue?

**Comment by XDRAGON2002** [comment]
Sure @iamhariom0228 go ahead!
