### ISSUE TITLE
Create a new route `/users/delete/<id>`

### ISSUE THREAD

**Issue by XDRAGON2002** [XDRAGON2002/iiit-gram#8]
Create a DELETE request handler that deletes the specified id object from the users array.

**Comment by Anukool1729** [comment]
Hi can you please assign me this issue.

**Comment by XDRAGON2002** [comment]
Hi @Anukool1729! Happy Hacktober!

This repo is a part of an activity created for the students of our institute so that they can learn more about opensource and contributions through actual hands on experience, although I'm sure you'll be able to find a bunch of issues that you can work on in other repositories.

**Comment by Aaroh1** [comment]
Hey @XDRAGON2002 ! Please assign this issue to me.

**Comment by Aaroh1** [comment]
Hey @XDRAGON2002 I've sent a pr that closes issue #14. Please review it

**Comment by XDRAGON2002** [comment]
> Hey @XDRAGON2002 I've sent a pr that closes issue #14. Please review it

Make the stated changes in your PR.

**Comment by Aaroh1** [comment]
Hey @XDRAGON2002 ! Can you assign this to me now?
