### ISSUE TITLE
Integrate mongodb atlas

### ISSUE THREAD

**Issue by XDRAGON2002** [XDRAGON2002/iiit-gram#9]
Integrate the mongoose library with the server so that we can start working with an actual database.

**Comment by romantic-sid** [comment]
plz assign  me this issue sir

**Comment by XDRAGON2002** [comment]
Hi @romantic-sid! Are you from our institute?
You most probably are but just want to confirm before assigning you.

**Comment by romantic-sid** [comment]
yes sir

**Comment by XDRAGON2002** [comment]
Well since most of the issues, in this repo are assigned at this point, we will have to finish up this issue ASAP, so that the new set of issues can be created.

P.S. In case this issue is not resolved in the next two days, I'll either create more issues that are independent of mongodb or add support for mongodb myself, moreover issues for frontend can be created now as well.

**Comment by codesmith25103** [comment]
Sir, can you assign me this issue?

**Comment by XDRAGON2002** [comment]
@romantic-sid are you working on this? If not @codesmith25103 can try this.

**Comment by romantic-sid** [comment]
Yes sir i am working on this

**Comment by XDRAGON2002** [comment]
@codesmith25103 This issue is already being worked upon, as most issues are taken up here, you can wait for a day or two for new issues to be created here and work on other repositories in the meanwhile.
